### ISSUE TITLE
Version bump?

### ISSUE THREAD

**Issue by SocalNick** [boxen/puppet-foreman#2]
Do you know what version of foreman this installs? I am getting an error when I kill foreman that appears to be resolved in 0.62.0 / https://github.com/ddollar/foreman/issues/332

```
^C/opt/boxen/foreman/lib/foreman/engine.rb:146:in `synchronize': can't be called from trap context (ThreadError)
    from /opt/boxen/foreman/lib/foreman/engine.rb:146:in `puts'
    from /opt/boxen/foreman/lib/foreman/engine.rb:36:in `block in start'
    from /opt/boxen/foreman/lib/foreman/engine.rb:123:in `call'
    from /opt/boxen/foreman/lib/foreman/engine.rb:123:in `wait2'
    from /opt/boxen/foreman/lib/foreman/engine.rb:123:in `watch_for_termination'
    from /opt/boxen/foreman/lib/foreman/engine.rb:41:in `start'
    from /opt/boxen/foreman/lib/foreman/cli.rb:33:in `start'
    from /opt/boxen/foreman/vendor/gems/thor-0.14.6/lib/thor/task.rb:22:in `run'
    from /opt/boxen/foreman/vendor/gems/thor-0.14.6/lib/thor/invocation.rb:118:in `invoke_task'
    from /opt/boxen/foreman/vendor/gems/thor-0.14.6/lib/thor.rb:263:in `dispatch'
    from /opt/boxen/foreman/vendor/gems/thor-0.14.6/lib/thor/base.rb:389:in `start'
    from /opt/boxen/foreman/bin/foreman:15:in `<main>'
```

**Comment by mroth** [comment]
The current version of this package installs 0.63.0, so this Issue is now out of date.
(I'l be opening a new issue for 0.67.0 though).
